version: "3"
services:
  rest:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db 
    networks:
      - frontend
      - backend
  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
networks:
  frontend:
  backend:
