version: "3"
services:
  rest-api:
    container_name: api
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo-db 
    networks:
      - frontend
      - backend
  mongo-db:
    container_name: db
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db
networks:
  frontend:
  backend:
volumes:
  mongodb_data:
